[package]
name = "native"
version = "0.1.0"
authors = ["matthew86707 <matt86707@Gmail.com>"]
edition = "2018"

[lib]
name = "ic_designer_native"
crate-type = ["dylib"]

[dependencies]
rustc_version = "0.2"

[build-dependencies]
rustc_version = "0.2"